version: '3.3'
services:
  boltz-backend:
    image: boltz/backend:latest
    container_name: boltz-backend
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    ports:
      - '9001:9001'
    volumes:
      - ./data/boltz-backend/config.toml:/boltz-backend/config.toml
      - ./data/boltz-backend/hardhat.config.ts:/boltz-backend/hardhat.config.ts
      - ./data/boltz-backend/home/otpSecret.dat:/root/.boltz/otpSecret.dat
      - ./data/boltz-backend/home/otpUri.txt:/root/.boltz/otpUri.txt
      - ./data/boltz-backend/home/seed.dat:/root/.boltz/seed.dat
      - ./volumes/bitcoind/backend1/regtest/.cookie:/boltz-backend/nodes/btc/.bitcoin-cookie
      - ./volumes/lnd/alice/tls.cert:/boltz-backend/nodes/lnd/certificates/tls.cert
      - ./volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon:/boltz-backend/nodes/lnd/macaroons/admin.macaroon
    depends_on:
      boltz-backend-setup:
        condition: service_healthy
  boltz-backend-setup:
    image: boltz/backend:latest
    container_name: boltz-backend-SETUP
    restart: "no"
    depends_on:
      # boltz-regtest:
      #   condition: service_started
      rskj:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ls"]
      interval: 20s
      timeout: 5s
      start_period: 140s
    volumes:
      - ./data/boltz-backend/config.toml:/boltz-backend/config.toml
      - ./data/boltz-backend/hardhat.config.ts:/boltz-backend/hardhat.config.ts
      - ./data/boltz-backend/home/otpSecret.dat:/root/.boltz/otpSecret.dat
      - ./data/boltz-backend/home/otpUri.txt:/root/.boltz/otpUri.txt
      - ./data/boltz-backend/home/seed.dat:/root/.boltz/seed.dat
    entrypoint: [ "bash", "-c", "cd /boltz-backend && npm run docker:rskj:deploy && /boltz-backend/bin/boltz-ethereum send 1000000000000 '0xABf0E4a3aB8628CAC2D0539679233B607c3c6f42' --provider http://host.docker.internal:4444 && /boltz-backend/bin/boltz-ethereum send 1000000000000 '0xABf0E4a3aB8628CAC2D0539679233B607c3c6f42' --token --provider http://host.docker.internal:4444 && sleep infinity"]
  rskj:
    image: rskj:latest
    container_name: RSK-Node
    ports:
      - '4444:4444'
      - '4445:4445'
    volumes:
      - ./data/rskj/database:/root/.rsk/regtest/database
      - ./data/rskj/local/node.conf:/usr/local/rskj/node.conf
      - ./data/rskj/local/logback.xml:/usr/local/rskj/logback.xml

  backend1:
    image: polarlightning/bitcoind:0.21.1
    container_name: polar-n1-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0
      -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1
      -listenonion=0 -fallbackfee=0.0002
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18445:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  alice:
    image: polarlightning/lnd:0.13.0-beta.rc3
    container_name: polar-n1-alice
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice
      --tlsextradomain=alice --tlsextradomain=polar-n1-alice --tlsextradomain=host.docker.internal
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10001:10009'
      - '9735:9735'
  bob:
    image: polarlightning/lnd:0.13.0-beta.rc3
    container_name: polar-n1-bob
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bob
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob
      --tlsextradomain=bob --tlsextradomain=polar-n1-bob --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/bob:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10002:10009'
      - '9739:9735'
  carol:
    image: polarlightning/lnd:0.13.0-beta.rc3
    container_name: polar-n1-carol
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: carol
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=carol --externalip=carol
      --tlsextradomain=carol --tlsextradomain=polar-n1-carol
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8084:8080'
      - '10003:10009'
      - '9740:9735'
